# Generated by Django 6.0.3 on 2026-03-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Teknoloji', 'Teknoloji'), ('Spor', 'Spor'), ('Eğitim', 'Eğitim'), ('Siyaset', 'Siyaset'), ('Sanat', 'Sanat'), ('Diğer', 'Diğer')], default='Diğer', max_length=50),
        ),
    ]
