# Generated by Django 6.0.3 on 2026-05-08 20:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='GEN', max_length=50, verbose_name='Ikon')),
                ('color', models.CharField(default='#00F0A0', max_length=7, verbose_name='Renk Kodu')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('text', models.TextField(verbose_name='Soru Metni')),
                ('question_type', models.CharField(choices=[('SINGLE', 'Tek Seçimli'), ('MULTIPLE', 'Çoklu Seçimli'), ('TEXT', 'Açık Uçlu Metin'), ('NUMBER', 'Sayısal'), ('RATING', 'Derecelendirme (1-5)'), ('YESNO', 'Evet / Hayır'), ('DATE', 'Tarih'), ('SLIDER', 'Kaydırma (0-100)')], default='SINGLE', max_length=20, verbose_name='Soru Tipi')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Yardım Metni')),
                ('min_value', models.IntegerField(default=0, verbose_name='Min Değer')),
                ('max_value', models.IntegerField(default=100, verbose_name='Max Değer')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('text', models.CharField(max_length=300, verbose_name='Seçenek Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(max_length=300, verbose_name='Anket Başlığı')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('access_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Erişim Kodu')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('PAUSED', 'Duraklatıldı'), ('CLOSED', 'Kapatıldı'), ('ARCHIVED', 'Arşivlendi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=20, verbose_name='Öncelik')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_public', models.BooleanField(default=True, verbose_name='Herkese Açık')),
                ('allow_anonymous', models.BooleanField(default=False, verbose_name='Anonim Yanıta İzin Ver')),
                ('require_location', models.BooleanField(default=False, verbose_name='Konum Zorunlu')),
                ('max_responses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maks. Yanıt Sayısı')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='Konum Adı')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='surveys.category', verbose_name='Kategori')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('session_id', models.UUIDField(default=uuid.uuid4, verbose_name='Oturum ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='Tarayıcı Bilgisi')),
                ('completion_time', models.DurationField(blank=True, null=True, verbose_name='Tamamlanma Süresi')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Yanıtlayan')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Yanıt',
                'verbose_name_plural': 'Yanıtlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Anket'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('text_answer', models.TextField(blank=True, verbose_name='Metin Yanıtı')),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sayısal Yanıt')),
                ('date_answer', models.DateField(blank=True, null=True, verbose_name='Tarih Yanıtı')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_answers', to='surveys.choice', verbose_name='Seçilen Seçenekler')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question', verbose_name='Soru')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response', verbose_name='Yanıt')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'unique_together': {('response', 'question')},
            },
        ),
    ]
